services:
  app:
    build: .
    tty: true
    ports:
      - "8000:8000"
    environment:
      - POETRY_VIRTUALENVS_CREATE=false
    command: poetry run uvicorn main:app --reload --host 127.0.0.1 --port 8000
